name: Build F1 APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Flet CLI
        run: pip install flet-cli

      - name: Build Android APK
        run: flet build apk src/main.py --module-name main
        
      - name: Save APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: f1-app-apk
          path: build/apk/*.apk
